name: JAVA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        environments: [ "dev", "qa", "prod" ]
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/hello-world-docker-action@v2
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Print output
        run: echo "Greet time was ${{ steps.hello.outputs.time }}"
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: true
      - name: run java step lol
        run: java HelloWorldApp.java
      - name: Deploy to ${{ matrix.environments }}
        run: |
          echo deploying to $AWS_ACCOUNT_NAME