name: Manual Approval Pipeline

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Your Build Step
        run: echo ${{ github.event.inputs.logLevel }}